### ISSUE TITLE
readthedocs docu needs an update

### ISSUE THREAD

**Issue by acbekoac** [seanthegeek/yaramail#2]
Hi,

read the docs [0] still gives the old/wrong install infos

pip3 install -U yaramail

cool project, thx

[0]
https://seanthegeek.github.io/yaramail/index.html#

**Comment by seanthegeek** [comment]
That command works. What is wrong about it?

**Comment by acbekoac** [comment]
not on my Ubuntu 20.04 box. had to enter 
pip3 install -U yara-mail --user

**Comment by seanthegeek** [comment]
Right. It depends on how you are installing it. If you're using a [Python virtual environment](https://docs.python.org/3/tutorial/venv.html) (and you should be) you don't need [--user], but if you want to install it as a utility for a user account, you use `--user`.
